name: cn-messaging-app

services:
  # Backend Service
  - name: backend
    github:
      repo: MuhammadMehroz786/JWT-Messaging-APP
      branch: main
      deploy_on_push: true
    source_dir: /backend

    build_command: pip install -r requirements.txt
    run_command: gunicorn app:app --bind 0.0.0.0:$PORT

    envs:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: ${SECRET_KEY}
        type: SECRET

    http_port: 8000

    instance_count: 1
    instance_size_slug: basic-xxs

  # Frontend Service (Static Site)
  - name: frontend
    github:
      repo: MuhammadMehroz786/JWT-Messaging-APP
      branch: main
      deploy_on_push: true
    source_dir: /frontend

    build_command: npm install && npm run build
    output_dir: build

    envs:
      - key: REACT_APP_API_URL
        value: ${backend.PUBLIC_URL}/api

    static_site:
      index_document: index.html
      error_document: index.html
